name: 🗓️ Auto-Generate Weekly Timesheet

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 09:00 UTC
  workflow_dispatch:

jobs:
  generate-timesheet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Neuroverse Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run timesheet generator
      run: |
        python3 scripts/auto_generate_timesheet.py

    - name: Commit new timesheet (if created)
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add weekly_notes/
        git diff --cached --quiet || git commit -m "📅 Auto-create new weekly timesheet"
        git push
