name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' # Adjust this version as necessary

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libssl-dev

    - name: Install .NET dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v2 # Ensure this version is correct
      with:
        name: test-results
        path: '**/TestResults/*.xml'
